// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk-TCopEyfkyN6-a8SEa82i-ihrYwLdso',
    appId: '1:353885364299:web:893bad75f6d6f7de5dadce',
    messagingSenderId: '353885364299',
    projectId: 'fir-9a013',
    authDomain: 'fir-9a013.firebaseapp.com',
    storageBucket: 'fir-9a013.appspot.com',
    measurementId: 'G-T998BM84SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCJgGCDdM3edyjWOmU69YdflXfwMRUwVY',
    appId: '1:353885364299:android:a5fd4acacca1425e5dadce',
    messagingSenderId: '353885364299',
    projectId: 'fir-9a013',
    storageBucket: 'fir-9a013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUm_1W8zIg2jLnbb4_GE2jXv8xH03T4KU',
    appId: '1:353885364299:ios:0270acd0dbed008e5dadce',
    messagingSenderId: '353885364299',
    projectId: 'fir-9a013',
    storageBucket: 'fir-9a013.appspot.com',
    iosBundleId: 'com.example.loginPageUsingClasses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUm_1W8zIg2jLnbb4_GE2jXv8xH03T4KU',
    appId: '1:353885364299:ios:dcbdc7a55ba6e4ef5dadce',
    messagingSenderId: '353885364299',
    projectId: 'fir-9a013',
    storageBucket: 'fir-9a013.appspot.com',
    iosBundleId: 'com.example.loginPageUsingClasses.RunnerTests',
  );
}
